import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import './scanlines.scss'
import Image from 'next/image'
import monitor from './monitor-border.webp'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Image
          src={monitor}
          alt=""
          fill={true}
          style={{
            zIndex: 20,
            pointerEvents: 'none'
          }}
        />
        <div className='scanlines'>
          {children}
        </div>
      </body>
    </html >
  )
}
